# (string) Title of your wiki
title: BuildCollection
demo_ver: 1.0.13
repository: TD2Builds/BuildCollection
#remote_theme: Drassil/git-wiki-theme@master
description: TD2 Builds and Docs
show_downloads: true
show_wiki_pages: true
show_wiki_pages_limit: 10
paginate: 5
paginate_path: "assets/blog/page:num"
blog_feature: true
show_wiki_posts: true
show_wiki_posts_limit: 5
logo_url: assets/images/1200px-Wikipedia-logo-v2.svg_.png
google_analytics:
git_branch: gh-pages
use_github_wiki: false
use_prose_io: true
service: github
search_engine: "js"
google_cse_token: 007197903287787072094:8rbvkeqo6qw
wiki_folder: "wiki"
permalink: /blog/posts/:year/:month/:day/:title:output_ext
site_root:

#
# Jekyll
#

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
  - jekyll-avatar
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jemoji
  - jekyll-gitlab-metadata
#
# INCLUDING HOOKS
# They are optional, change them only if you need
# Check wiki documentation to learn how they work
#

# inc_before_toc :
# inc_after_toc :
# inc_before_content :
# inc_after_content :
# inc_before_footer :
# inc_after_footer :
# inc_before_head :
# inc_after_head :
# inc_before_meta :
# inc_after_meta :
# inc_before_scripts :
# inc_after_scripts :
# inc_before_styles :
# inc_after_styles :
# inc_before_header :
# inc_after_header :
# inc_before_tail :
# inc_after_tail :
# inc_before_tools :
# inc_after_tools :

# inc_before_page_list :
# inc_after_page_list :
# inc_before_post_list :
# inc_after_post_list :
